# docker-compose.prod.yml
version: '3.7'

services:
  web:
    container_name: wagtail
    restart: unless-stopped
    build:
      context: app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8009
    volumes:
      - ./var/www/static:/home/app/web/static
      - ./var/www/media:/home/app/web/media
    ports:
      - "8009:8009/tcp"
    env_file:
      - .env.prod

  db:
    container_name: wagtail-postgres
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    network_mode: "service:web"
